# Generated by Django 3.2.8 on 2021-11-01 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Temperature',
        ),
    ]
