# Generated by Django 3.2.8 on 2021-11-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_article_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='humidity',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
    ]
