# Generated by Django 3.2.9 on 2021-11-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_temperature_humidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='location',
            field=models.CharField(default='Station 2', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperature',
            name='name',
            field=models.CharField(default='Generator 1', max_length=100),
            preserve_default=False,
        ),
    ]
